final products = [
  {
    'title': 'Nike Shoes',
    'Price': 6999.0,
    'size': [8, 9, 10, 11],
    'id': '0',
    'imageURL': 'assets/images/nike6999.png',
    'company': 'Nike',
  },
  {
    'title': 'Puma Shoes',
    'Price': 6999.0,
    'size': [8, 9, 10, 11],
    'id': '1',
    'imageURL': 'assets/images/puma.png',
    'company': 'Puma',
  },
  {
    'title': 'Adidas Shoes',
    'Price': 6999.0,
    'size': [8, 9, 10, 11],
    'id': '2',
    'imageURL': 'assets/images/adidas.png',
    'company': 'Adidas',
  },
  {
    'title': 'Reebok Shoes',
    'Price': 6999.0,
    'size': [8, 9, 10, 11],
    'id': '3',
    'imageURL': 'assets/images/reebok.png',
    'company': 'Reebok',
  },
  {
    'title': 'Under Armour Shoes',
    'Price': 6999.0,
    'size': [8, 9, 10, 11],
    'id': '4',
    'imageURL': 'assets/images/underarmour8999.png',
    'company': 'Under Armour',
  },
];
